/*  Table of Contents for Article Component 
    The Table of Content items are generated by the heading tags in the Article .md file. Heading depth can be modified.
*/

// Import React and Gatsby Elements
import React from 'react'
import PropTypes from 'prop-types'

// Import Utilities and Style Elements
import { TocHeader, TocUl, TocLi, TocLink } from '../elements/'

const ToC = ({ headings }) => (

  <nav aria-labelledby="id-1" className="sticky-inner">
    <TocUl>
      <TocHeader id="id-1">Table of Contents</TocHeader>
        {headings.map(heading => {
          if (heading.depth > 3) {
            return <div />
          }
          return (
            <TocLi key={heading.value}>
              <TocLink href={`#${heading.value.replace(/\s+/g, "-").toLowerCase()}`} 
                aria-label="Table of Contents"
                role="button"
              >
                {heading.value}
              </TocLink>
            </TocLi>
          )
        })}
    </TocUl>
  </nav>
)

ToC.propTypes = {
  headings: PropTypes.array.isRequired,
}

export default ToC